### ISSUE TITLE
What is the Balance section for 

### ISSUE THREAD

**Issue by fredhampton** [DemocracyEarth/sovereign#124]
In the members profile section there is a balance area.
What is the balance....is this the number of votes ?
How can this be edited changed ?

Thanks

**Comment by jetlej** [comment]
+1, this was very unclear to me

**Comment by santisiri** [comment]
It is the votes you can directly delegate to a user by viewing their profile

**I'm actively working on this**, so that's why it doesn't make much sense right now. The `power` component is specifically the file and it will be drastically improved as a feature. Right now is just boilerplate content to test look and feel. 

So.. it makes sense that is unclear. Still work in progress.
