### ISSUE TITLE
Deploy information website. Hard deadline: 05/04

### ISSUE THREAD

**Issue by paulamlb** [DemocracyEarth/sovereign#284]
Colombian referendum website: http://plebiscitodigital.co/
@santisiri  wheres the code for that? 
What should the domain be? Maybe something like "eleccioneslegitimas"
We'll have a video by then... I will work on the content.

**Comment by medied** [comment]
Something like 'eleccioneslegitimas' is interesting but I think it's too prone to cause confusion, just because 'elecciones' comes from 'to elect' and hence people could come to site already thinking someone is going to be elected. Some ideas thinking out loud: 

venezuelavota.ve
votavenezuela.ve 
votavz.la
plebiscitodigital.ve
venezuelademocratica.ve
venezuelalibre.ve

**Comment by medied** [comment]
We should aim to have a basic website ready by the time we publish Medium article, so we can link it in the article and point people to it. We can add video to the website once it's ready, don't think we need to wait for the video.

@santisiri let's sync about the code for http://plebiscitodigital.co/ - I can take care of that

**Comment by santisiri** [comment]
i like the simple approach of http://venzuela.democracy.earth

@medied the landing for plebiscito digital i have it on http://webflow.com, create a user there and i'll send it to you.

**Comment by medied** [comment]
@santisiri this is me - https://webflow.com/medied

I guess we could have venezuela.democracy.earth redirect to the webflow site until we 'open up' parallel voting, and while parallel voting period is active the info site could be found at a different url like info-venezuela.democracy.earth. Is something like that what you were thinking of? I like that simplicity.

**Comment by aecc** [comment]
@medied @paulamlb @santisiri  Maybe this is a discussion out of the scope of this github issue, however, my 2 satoshis: it is elections what's gonna happen on 20th of May, legitimate or not. Shouldn't we allow people to vote in the way they want to vote? (to select a president, free of coercion, in a safe and secure manner and for the candidates they want to vote). We could add multiple "extra questions" as well to the vote, but I like the idea of replicating the election day with the "guarantees" Venezuelans deserve.

**Comment by paulamlb** [comment]
Hi Alessandro! @aecc Can you explicit what kind of guarantees?

**Comment by aecc** [comment]
hi @paulamlb, the ones I just mentioned: "to select a president, free of coercion, in a safe and secure manner and for the candidates they want to vote". I'm sure you are aware that one of the most important issues why people are reluctant to vote is because some of the most important leaders in Venezuela are actually banned from the election. This could be a way where people who want to express they support for them can do it. My whole point is that exactly what people want to do is to be able to "elect" someone else for the government and we should give them that opportunity.

**Comment by santisiri** [comment]
@medied here's all the code for the landing we did back then: https://www.dropbox.com/s/r35eioge7nxgm5e/colombiaearth.webflow.zip?dl=0

**Comment by medied** [comment]
Yea let's continue that conversation in #287

**Comment by paulamlb** [comment]
@medied were you able to get that?

**Comment by medied** [comment]
http://www.venezuelaproponecambio.com/
