### ISSUE TITLE
Set up crypto jurisdictions

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#359]
How to handle crypto jurisdictions, set up domain instances, etc

**Comment by santisiri** [comment]
Most cost-effective approach is using $CRYPTO and operating that as a hashtag on the `/token/crypto` feed as it has already been implemented. 

ie: If a proposal mentions $EOS, editor suggests to change vote token to $EOS (instead of default $VOTE). We should add this to the schema of `Contracts`. Possibily creating a specific schema for `Token` like we did for other stuff.

**Comment by santisiri** [comment]
Jurisdictions have been effectively implemented.

* `consitutency` component is an editor that allows to customize jurisdiction based on country, coin or domain.
* `electorate` is a component that checks if `Meteor.user()` has the criteria required by the `constituency` of a `contract` and displays such state.

* `/lib/token.js` cointains corpus for crypto entities. This can and should be updated in the future.

Only left thing is simply signalling and enabling/disabling vote if user meets `constituency` criteria.

<img width="340" alt="screenshot 2018-07-20 19 59 28" src="https://user-images.githubusercontent.com/2153166/43017944-351f5cc6-8c58-11e8-862a-7f1349095a3d.png">
