### ISSUE TITLE
Update user schema to add appropriate token structure

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#370]
Daemon will communicate with EVM and Sovereign to keep numbers in sync (see #364), this user schema update is needed to address the connection with the daemon

**Comment by medied** [comment]
Brainstormed with @LucasIsasmendi what an appropriate token structure could look like. After looking more closely at the current state of the user schema though I think the [Wallet](https://github.com/DemocracyEarth/sovereign/blob/master/imports/api/users/Wallet.js) sub-schema for each user profile offers much of what we need.

The rough structure we envisioned we'd need:

```
token: [
    {
        publickey: STRING,
        ticker: STRING,
        balance: NUMBER,
        voted: NUMBER,
        delegated: NUMBER
    }
]
```

What's currently there with Wallet.js:

```
wallet: {
    available: NumberLong("1000"),
    currency: "VOTES",
    address: [
    {
        hash: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXee39e95",
        collectiveId: "aiejndhaiqnlajdP2x"
    }
    ],
    ledger: [],
    balance: NumberLong("1000"),
    placed: NumberLong("0")
},
```

Maybe what's most appropriate is to make it an array of wallets, something like: 

```
wallet: [
    {
        available: NumberLong("1000"),
        currency: "VOTES",
        address: [
            {
            hash: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXee39e95",
            collectiveId: "aiejndhaiqnlajdP2x"
            }
        ],
        ledger: [],
        balance: NumberLong("1000"),
        placed: NumberLong("0")   
    },
    {
        available: NumberLong("1000"),
        currency: "DOGE",
        address: [
            {
            hash: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXmsj183h",
            collectiveId: "palein1084pandldoen"
            }
        ],
        ledger: [],
        balance: NumberLong("1000"),
        placed: NumberLong("0")   
    },
]
```

@santisiri can you provide some insight to:

- what does the `address` array represent in this case? 
- does `placed` represent both voted and delegated tokens?
- what is the purpose of `ledger` array?

Looking for feedback and thoughts overall

**Comment by medied** [comment]
Playing around in branch `crypto-signaling`

**Comment by santisiri** [comment]
The good news is that `wallet` is there mostly as a placeholder and not really required on any part of the product as it is right now. In `transactions.js` there is a `processTransaction` function that does update the status of `wallets` in both `Contracts` and `Users` but that's about it. 

This means that this refactor is doable and shouldn't be very expensive to implement. 

I think that doing an array of `wallet` makes plenty of sense. Probably we need to do a Schema specific to the `wallet` object following the established guidelines you mention in the first comment. 

> what does the address array represent in this case?

A placeholder to allow for crypto addresses in the future. So far, it's never interpreted anywhere on the software. So this is future that has actually just became the present. 

> does placed represent both voted and delegated tokens?

`placed` means tokens that have been staked, yes.. in that sense it covers the accounting for both: delegated and voted. 

> what is the purpose of ledger array?

Another placeholder that's never used. Just a way of persisting the historical record of transactions for a given contract or user.. I ended up doing the `Transactions` collection instead and calling that when needed with a query. But since that can lead to low performance, now the only real thing that keeps track of votes in `Contracts` is the `tally` object you can find in the schema that includes two types of objects `choice` (to account for ballot voting) and `voter` (to account by who voted). The `tally` object is only used in `Contracts` and not present in `Users`. It's simply an optimization that makes the app run faster and less calls to the db.
