### ISSUE TITLE
Could not install from "node_modules/chimp/cucumber@github:xolvio/cucumber-js" as it does not contain a package.json file

### ISSUE THREAD

**Issue by marsrobertson** [DemocracyEarth/sovereign#477]
Cannot do `npm install`

Similar - https://github.com/ansible/ansible/issues/54293 - but also not fixed.

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/chimp/cucumber@github:xolvio/cucumber-js#cf953cb5b5de30dbcc279f59e4ebff3aa040071c" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ms/.npm/_logs/2019-09-15T18_04_15_792Z-debug.log
```

### Full error log
[2019-09-15T18_04_15_792Z-debug.log](https://github.com/DemocracyEarth/sovereign/files/3614101/2019-09-15T18_04_15_792Z-debug.log)

**Comment by Cleberw3b** [comment]
This is related to [Chimp](https://www.npmjs.com/package/chimp) depency package where package.json is missing.

I see that chimp has been splitted into 2 new projects as described [here](https://medium.com/@sam_hatoum/the-future-of-chimp-js-e911f8e9aaa6).

But after some tests I figured that the problem is within dependencies build and could only build using node v8.16.2
