### ISSUE TITLE
Warnings on npm install

### ISSUE THREAD

**Issue by domi41** [DemocracyEarth/sovereign#96]
`npm install`

yields

```
npm WARN sovereign No repository field.
npm WARN sovereign No license field.
```

This can be easily fixed by adding a `repository` and a `license` field in `package.json`. See respectively https://docs.npmjs.com/files/package.json#repository and https://docs.npmjs.com/files/package.json#license

**Comment by fredhampton** [comment]
can the suggested changes be added to the distro ?


On December 25, 2016 at 2:26:18 AM, Dominique Merle (notifications@github.com) wrote:

npm install

yields

npm WARN sovereign No repository field.
npm WARN sovereign No license field.
This can be easily fixed by adding a repository and a license field in package.json. See respectively https://docs.npmjs.com/files/package.json#repository and https://docs.npmjs.com/files/package.json#license

**Comment by domi41** [comment]
I can create a Pull Request if you want ?

**Comment by fredhampton** [comment]
That would be great !


On December 26, 2016 at 3:25:27 AM, Dominique Merle (notifications@github.com) wrote:

I can create a Pull Request if you want ?

**Comment by domi41** [comment]
It's almost done, I'm hitting a snag here :

**Comment by domi41** [comment]
Let's move the discussion to the PR #97
